[pytest]
;-n 2 --dist=loadfile
;--reruns=2 --reruns-delay=10
addopts = -sv --alluredir ./report/data --clean-alluredir -n 2 --dist=loadfile
testpaths = ./testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_format = %(asctime)s %(levelname)s [%(name)s] [%(filename)s (%(funcName)s:%(lineno)d) - %(message)s]
log_date_format = %Y-%m-%d %H:%M:%S